### PR TITLE
Fix a typo in getUint32Array.

### PR DESCRIPTION
**Pull request by yenatch**
I seem to be having trouble with line endings. Let me know if I need to fix it here.

### CODE REVIEW

**Comment by grantgalitz** [comment]
Damn nice catch. This was a bad one. Need to review which parts of the emulator used this then.

**Comment by grantgalitz** [comment]
Stupid mobile interface. I clicked the wrong button at first and had to reopen and merge.

**Comment by grantgalitz** [comment]
Also editors hate me when switching between Mac and windows. One has a default of tab character when indenting, the other adds 4 spaces. Not to mention that some editors add the return carriage control character with the new line character while others just do new line. I'll go through with a search and replace to clean up the different control characters. Goddamn every editor wants to use its own line control character encoding

**Comment by grantgalitz** [comment]
Tabs are supposed to be 4 spaces and not the tab control character, as spaces show up with alignment better across multiple editors. GitHub commit viewing shows this

**Comment by TazeTSchnitzel** [comment]
They're all configurable, the defaults are what vary.

For line-ending conversion, try `dos2unix`.

**Comment by grantgalitz** [comment]
Yeah. It's that I tend to use the defaults a lot that screws with me. Indeed they are configurable though. Hard to tell in one of the editors I use as tabs and spaces render the same on it.

**Pull request merged**
